### ISSUE TITLE
Missing results in GET `/snomed-ct/v3/{path}/members`

### ISSUE THREAD

**Issue by martinmart92** [b2ihealthcare/snow-owl#1030] opened 2022-06-06 16:44 UTC
**Describe the bug**
When querying for this endpoint with a list of 120 `referencedComponentId` values, SnowOwl only returns 99 results.

**To Reproduce**

curl command:

```
curl --location --request GET 'https://localhost/snowowl/snomed-ct/v3/{path}/members?referenceSet=723562003&expand=referencedComponent(expand(fsn(),pt()))&active=true&limit=2000&referencedComponentId=246456000&referencedComponentId=246112005&referencedComponentId=704324001&referencedComponentId=272741003&referencedComponentId=42752001&referencedComponentId=363589002&referencedComponentId=246090004&referencedComponentId=704321009&referencedComponentId=732945000&referencedComponentId=774158006&referencedComponentId=118170007&referencedComponentId=116676008&referencedComponentId=363698007&referencedComponentId=246513007&referencedComponentId=246093002&referencedComponentId=405816004&referencedComponentId=260507000&referencedComponentId=784276002&referencedComponentId=246196007&referencedComponentId=363700003&referencedComponentId=762951001&referencedComponentId=371881003&referencedComponentId=733930001&referencedComponentId=736474004&referencedComponentId=408730004&referencedComponentId=704327008&referencedComponentId=246075003&referencedComponentId=774081006&referencedComponentId=363714003&referencedComponentId=860779006&referencedComponentId=260686004&referencedComponentId=733723002&referencedComponentId=363703001&referencedComponentId=405813007&referencedComponentId=766953001&referencedComponentId=370133003&referencedComponentId=370134009&referencedComponentId=410675002&referencedComponentId=260870009&referencedComponentId=733933004&referencedComponentId=408731000&referencedComponentId=405814001&referencedComponentId=732947008&referencedComponentId=704322002&referencedComponentId=424244007&referencedComponentId=733724008&referencedComponentId=118169006&referencedComponentId=827081001&referencedComponentId=704325000&referencedComponentId=288556008&referencedComponentId=736476002&referencedComponentId=246501002&referencedComponentId=704319004&referencedComponentId=363701004&referencedComponentId=363709002&referencedComponentId=370131001&referencedComponentId=424361007&referencedComponentId=762949000&referencedComponentId=736473005&referencedComponentId=774160008&referencedComponentId=370132008&referencedComponentId=733931002&referencedComponentId=418775008&referencedComponentId=116686009&referencedComponentId=704320005&referencedComponentId=726633004&referencedComponentId=860781008&referencedComponentId=363713009&referencedComponentId=733722007&referencedComponentId=766939001&referencedComponentId=363704007&referencedComponentId=718497002&referencedComponentId=419066007&referencedComponentId=774163005&referencedComponentId=766954007&referencedComponentId=320081000221109&referencedComponentId=719715003&referencedComponentId=424226004&referencedComponentId=733928003&referencedComponentId=774159003&referencedComponentId=763032000&referencedComponentId=246514001&referencedComponentId=363699004&referencedComponentId=732944001&referencedComponentId=736518005&referencedComponentId=704323007&referencedComponentId=363710007&referencedComponentId=840560000&referencedComponentId=719722006&referencedComponentId=320091000221107&referencedComponentId=408729009&referencedComponentId=736475003&referencedComponentId=704326004&referencedComponentId=425391005&referencedComponentId=255234002&referencedComponentId=836358009&referencedComponentId=47429007&referencedComponentId=732943007&referencedComponentId=411116001&referencedComponentId=363702006&referencedComponentId=246454002&referencedComponentId=738774007&referencedComponentId=774161007&referencedComponentId=766952006&referencedComponentId=370130000&referencedComponentId=424876005&referencedComponentId=736472000&referencedComponentId=408732007&referencedComponentId=127489000&referencedComponentId=118171006&referencedComponentId=263502005&referencedComponentId=405815000&referencedComponentId=732946004&referencedComponentId=370129005&referencedComponentId=733932009&referencedComponentId=733725009&referencedComponentId=118168003&referencedComponentId=840562008&referencedComponentId=370135005&referencedComponentId=726542003' \
--header 'Accept: application/json' \
--header 'Authorization: Basic <notForGithub>'
```

I get the following result:
```
{
    "items":
    [ <NON-EMPTY ITEM LIST HERE with 99 elements> ],
    "searchAfter": "AoE_BWZlMTQzNDZkLWZkMjYtNDlhYi1hOWRiLWJhNzRmOGVjYTllZQ==",
    "limit": 2000,
    "total": 99
}
```
I expected a "total" with a value of 120, and 120 elements in the "items" field.
As an example, `363702006` is absent from the returned items. 

Interestingly, if I move this input parameter `referencedComponentId=363702006` in the curl query at the beginning of the list, it is now returned. Therefore, the order of the `referencedComponentId` input parameters seems to be taken into account.

In a subsequent call, I've tried to call again with the `searchAfter` value in the `searchAfter` input parameter, in an intent to paginate, but it returned exactly the same JSON result as the first call.

Useful things to include in the report:
* Example `snowowl.yml` configuration: TODO

**Version**
 - Snow Owl Version: `v7.17.6`
 - Elasticsearch Version (external): AWS ES `7.7` 

**Additional context**
N/A

**Comment by cmark** [comment] 2022-06-07 10:55
Hi @martinmart92,

Thanks for reporting the issue, we will take a look and get back to you shortly.

Cheers,
Mark

**Comment by martinmart92** [comment] 2022-06-07 16:00
Thank you @cmark ! Any questions or if you need more details from my side, please do feel free to ask.

**Comment by cmark** [comment] 2022-06-08 10:17
@martinmart92 do you happen to know the edition/extension you were querying with that request? Is it a SNOMED International content or perhaps the UK Edition?

I did try that query on our latest release versions (7.19.2 and 8.3.0) using the SNOMED International Edition and they both return 112 matches for the 120 referencedComponentIds. The difference is probably coming from the fact that some IDs are only present in certain editions/extensions, that's why I'm asking.
We will try to create an environment with the exact versions using the elasticsearch-oss:7.7.0 image and import the content you provide. Hopefully, that helps reproduce the bug.

**Comment by martinmart92** [comment] 2022-06-09 11:10
@cmark Thanks Mark for looking at this! 

So, I was querying the UK edition 2021-11-24 based on International edition 2021-01-31.
However, note that when I changed the order of the input parameters, the expected result does appear, which made me think of a bug in SnowOwl's code or config, rather than an issue related to the data itself. 

cf in my initial message: 
> Interestingly, if I move this input parameter referencedComponentId=363702006 in the curl query at the beginning of the > list, it is now returned. Therefore, the order of the referencedComponentId input parameters seems to be taken into account.

**Comment by cmark** [comment] 2022-06-09 11:33
> So, I was querying the UK edition 2021-11-24 based on International edition 2021-01-31. However, note that when I changed the order of the input parameters, the expected result does appear, which made me think of a bug in SnowOwl's code or config, rather than an issue related to the data itself.

Yes, I understand that, it's just it does not happen anymore or at least we were unable to reproduce it so far. Thanks for the information regarding the SNOMED content, we will try to reproduce it with the exact version and data and get back to you.

Cheers,
Mark

**Comment by cmark** [comment] 2022-06-09 11:55
Another question, does this happen when you use the `POST /:path/members/search` endpoint where a JSON body describes the query instead of using URL query parameters?

**Comment by martinmart92** [comment] 2022-06-09 13:00
@cmark thanks! We plan to upgrade to the latest version of SnowOwl as soon as possible. 

About the POST endpoint: We do not use the POST endpoint in our codebase (yet), so I don't know (yet), however I'll try it as soon as I can

**Comment by cmark** [comment] 2022-06-10 08:46
Hi @martinmart92,

Just a small update.

Specifying too many query parameters will result in an `HTTP 431 Request Header Fields Too Large` error in Snow Owl. In this case, it is recommended to switch to the POST endpoint and use that for querying.

Do you have any reverse proxy in front of the Snow Owl service? Some implementations by default simply truncate long URLs when proxying HTTP requests which could be the source of the problem. Also, custom rewrite rules might rewrite the URL incorrectly, truncating it to a fixed size length instead of preserving the original URL.

I hope this helps.

Cheers,
Mark

**Comment by cmark** [comment] 2022-08-13 11:37
Hi @martinmart92,

I'm going to close this one as we think the original issue is invalid. Feel free to reopen this or move it to a discussion if you'd like to.

Cheers,
Mark

**Closed as completed by cmark** 2022-08-13 11:37 UTC
Labels: bug
