### ISSUE TITLE
Error while running ./bin/snowowl.sh with snow-owl 7.1.0

### ISSUE THREAD

**Issue by ampaho** [b2ihealthcare/snow-owl#415] opened 2019-10-28 02:59 UTC
I'm getting this error after runing `./bin/snowowl.sh` while trying to install snow-owl 7.1.0 from the binary. I downloaded, unarchived the tar.gz.

Any hints?

```
snow-owl-oss-7.1.0.201909021539$ ./bin/snowowl.sh
~/opt/snow-owl-oss-7.1.0.201909021539 ~/opt/snow-owl-oss-7.1.0.201909021539
Java HotSpot(TM) 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
[2019-10-27T22:50:55.356] ERROR  Container: d19684d1-91bf-4ad2-8cf3-5e27b28ac3c5 snowowl        com/b2international/index/revision/Hooks$PreCommitHook java.lang.NoClassDefFoundError: com/b2international/index/revision/Hooks$PreCommitHook
 at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
 at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3142)
 at java.base/java.lang.Class.getConstructor0(Class.java:3347)
 at java.base/java.lang.Class.newInstance(Class.java:571)
 at com.b2international.commons.extension.ClassPathScanner.lambda$4(ClassPathScanner.java:156)
 at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
 at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
 at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
 at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
 at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
 at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
 at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
 at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
 at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
 at com.b2international.commons.extension.ClassPathScanner.instantiate(ClassPathScanner.java:162)
 at com.b2international.commons.extension.ClassPathScanner.getComponentsBySuperclass(ClassPathScanner.java:147)
 at com.b2international.snowowl.core.SnowOwl.<init>(SnowOwl.java:108)
 at com.b2international.snowowl.core.SnowOwl.create(SnowOwl.java:188)
 at com.b2international.snowowl.server.product.ServerProductActivator.start(ServerProductActivator.java:50)
 at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:842)
 at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
 at java.base/java.security.AccessController.doPrivileged(AccessController.java:552)
 at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:834)
 at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:791)
 at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1013)
 at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:365)
 at org.eclipse.osgi.container.Module.doStart(Module.java:598)
 at org.eclipse.osgi.container.Module.start(Module.java:462)
 at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$1.run(ModuleContainer.java:1820)
 at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$2$1.execute(EquinoxContainerAdaptor.java:150)
 at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1813)
 at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1770)
 at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1735)
 at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1661)
 at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
 at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
 at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
Caused by: java.lang.ClassNotFoundException: An error occurred while automatically activating bundle com.b2international.index (11).
 at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:126)
 at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:570)
 at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:330)
 at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:396)
 at org.eclipse.osgi.internal.loader.sources.SingleSourcePackage.loadClass(SingleSourcePackage.java:41)
 at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:470)
 at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:423)
 at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:415)
 at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:155)
 at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 37 common frames omitted
Caused by: org.osgi.framework.BundleException: Exception in com.b2international.index.Activator.start() of bundle com.b2international.index.
 at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:863)
 at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:791)
 at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1013)
 at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:365)
 at org.eclipse.osgi.container.Module.doStart(Module.java:598)
 at org.eclipse.osgi.container.Module.start(Module.java:462)
 at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:493)
 at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:117)
	... 46 common frames omitted
Caused by: java.lang.RuntimeException: java.lang.NoSuchFieldException: modifiers
 at com.b2international.index.Activator.withTccl(Activator.java:113)
 at com.b2international.index.Activator.start(Activator.java:63)
 at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:842)
 at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
 at java.base/java.security.AccessController.doPrivileged(AccessController.java:552)
 at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:834)
	... 53 common frames omitted
Caused by: java.lang.NoSuchFieldException: modifiers
 at java.base/java.lang.Class.getDeclaredField(Class.java:2416)
 at com.b2international.index.Activator.lambda$0(Activator.java:76)
 at com.b2international.index.Activator.withTccl(Activator.java:110)
 ... 58 common frames omitted
```

**Comment by cmark** [comment] 2019-10-28 08:07
Hi @ampaho,

What is the Java version you are trying to use?

Best,
Mark

**Comment by cmark** [comment] 2019-10-28 08:12
Hi @ampaho, 

It looks like the `Field.modifiers` field changed from an actual field to constant in Java 12 and that throws an error when you try to modify it via reflection.

See related bug report:
https://bugs.openjdk.java.net/browse/JDK-8217225

I recommend using the latest LTS version of the OpenJDK, which should be available on most operating systems.

Cheers,
Mark

**Comment by ampaho** [comment] 2019-10-28 11:16
> 
> What is the Java version you are trying to use?
> 

Hi @cmark 

```
$ java -version
java version "12.0.2" 2019-07-16
Java(TM) SE Runtime Environment (build 12.0.2+10)
Java HotSpot(TM) 64-Bit Server VM (build 12.0.2+10, mixed mode, sharing)

$ echo $JAVA_HOME
/Library/Java/JavaVirtualMachines/jdk-12.0.2.jdk/Contents/Home
```

And I'm on Mac OSX 10.14 (Mojave).

Thanks!

**Comment by psiotwo** [comment] 2019-10-29 08:07
I got the same exception on OpenJDK 13 (not surprising, as per @cmark's note). Now trying on OpenJDK 11 which gives me the following stacktrace. Any idea?

[2019-10-29T08:04:33.460] INFO   Container: 2a0e0caf-5199-451e-97dc-998ab1b77422 org.hibernate.validator.internal.util.Version                    HV000001: Hibernate Validator 5.1.1.Final 
[2019-10-29T08:04:33.836] ERROR  Container: 2a0e0caf-5199-451e-97dc-998ab1b77422 snowowl                                                          null java.lang.ExceptionInInitializerError: null
	at org.hibernate.validator.messageinterpolation.ResourceBundleMessageInterpolator.interpolateExpression(ResourceBundleMessageInterpolator.java:341)
	at org.hibernate.validator.messageinterpolation.ResourceBundleMessageInterpolator.interpolateMessage(ResourceBundleMessageInterpolator.java:279)
	at org.hibernate.validator.messageinterpolation.ResourceBundleMessageInterpolator.interpolate(ResourceBundleMessageInterpolator.java:182)
	at org.hibernate.validator.internal.engine.ValidationContext.interpolate(ValidationContext.java:362)
	at org.hibernate.validator.internal.engine.ValidationContext.createConstraintViolation(ValidationContext.java:271)
	at org.hibernate.validator.internal.engine.ValidationContext.createConstraintViolations(ValidationContext.java:232)
	at org.hibernate.validator.internal.engine.constraintvalidation.ConstraintTree.validateSingleConstraint(ConstraintTree.java:291)
	at org.hibernate.validator.internal.engine.constraintvalidation.ConstraintTree.validateConstraints(ConstraintTree.java:133)
	at org.hibernate.validator.internal.engine.constraintvalidation.ConstraintTree.validateConstraints(ConstraintTree.java:91)
	at org.hibernate.validator.internal.metadata.core.MetaConstraint.validateConstraint(MetaConstraint.java:84)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateConstraint(ValidatorImpl.java:525)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateConstraintsForDefaultGroup(ValidatorImpl.java:465)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateConstraintsForCurrentGroup(ValidatorImpl.java:429)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateInContext(ValidatorImpl.java:381)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validate(ValidatorImpl.java:184)
	at com.b2international.commons.validation.ApiValidation$1.validate(ApiValidation.java:103)
	at com.b2international.commons.config.ConfigurationFactory.validate(ConfigurationFactory.java:234)
	at com.b2international.commons.config.ConfigurationFactory.build(ConfigurationFactory.java:160)
	at com.b2international.commons.config.ConfigurationFactory.build(ConfigurationFactory.java:248)
	at com.b2international.commons.config.ConfigurationFactory.build(ConfigurationFactory.java:151)
	at com.b2international.commons.config.ConfigurationFactory.resolveModuleConfigs(ConfigurationFactory.java:190)
	at com.b2international.commons.config.ConfigurationFactory.build(ConfigurationFactory.java:158)
	at com.b2international.commons.config.ConfigurationFactory.build(ConfigurationFactory.java:248)
	at com.b2international.commons.config.ConfigurationFactory.build(ConfigurationFactory.java:112)
	at com.b2international.snowowl.core.SnowOwl.createConfiguration(SnowOwl.java:231)
	at com.b2international.snowowl.core.SnowOwl.<init>(SnowOwl.java:112)
	at com.b2international.snowowl.core.SnowOwl.create(SnowOwl.java:188)
	at com.b2international.snowowl.server.product.ServerProductActivator.start(ServerProductActivator.java:50)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:842)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:834)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:791)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1013)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:365)
	at org.eclipse.osgi.container.Module.doStart(Module.java:598)
	at org.eclipse.osgi.container.Module.start(Module.java:462)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$1.run(ModuleContainer.java:1820)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$2$1.execute(EquinoxContainerAdaptor.java:150)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1813)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1770)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1735)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1661)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
Caused by: javax.el.ELException: Provider com.sun.el.ExpressionFactoryImpl not found
	at javax.el.FactoryFinder.newInstance(FactoryFinder.java:101)
	at javax.el.FactoryFinder.find(FactoryFinder.java:197)
	at javax.el.ExpressionFactory.newInstance(ExpressionFactory.java:189)
	at javax.el.ExpressionFactory.newInstance(ExpressionFactory.java:160)
	at org.hibernate.validator.internal.engine.messageinterpolation.InterpolationTerm.<clinit>(InterpolationTerm.java:59)
	... 46 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.sun.el.ExpressionFactoryImpl cannot be found by com.b2international.commons_7.1.0
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:512)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:423)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:415)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at javax.el.FactoryFinder.newInstance(FactoryFinder.java:87)
	... 50 common frames omitted

**Comment by cmark** [comment] 2019-10-29 08:17
Hi @ampaho,

Could you please try with the latest OpenJDK 11 or with Docker using the following image with the tag `7.1.0` or `latest`?
https://hub.docker.com/r/b2ihealthcare/snow-owl-oss/tags

@psiotwo Which Snow Owl package are you trying to use? Could you please also try the docker image?

There is a `7.x` docker image as well, which is the latest build from the `7.x` branch. A new image should be up soon, which has the fix for the reflection issue mentioned above. It would be great if you could try that as well, thanks!

Keep in mind, so far we have only tried and used the LTS version of Java, more specifically, the OpenJDK Java 11.0.2, which can be downloaded from here: 
https://jdk.java.net/archive/

Cheers,
Mark

**Comment by psiotwo** [comment] 2019-11-03 09:51
Hi @cmark,

thank you.

My findings:
- I am able to run the docker image (`b2ihealthcare/snow-owl`) successfully, but SNOMEDCT Intl 20190131 import fails on heap space for embedded ES - exploring now how to configure it
- I am able to run 7.1.0 on OpenJDK 11.0.2. When trying to import SNOMEDCT Intl 20190131, I successfully create import metadata by POST /imports but upon POST /imports/3c8ed4c1-5ecc-4275-a539-cb317819161c/archive I get HTTP response 204! but the logs shows
```
[2019-11-03T09:46:44.272] ERROR eventbus-118                                     c.b2international.snowowl.snomed.api.impl.SnomedRf2ImportService Error during the import of: 3c8ed4c1-5ecc-4275-a539-cb317819161c java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics
	at org.mapdb.DBMaker.fileDB(DBMaker.kt)
	at com.b2international.snowowl.snomed.datastore.request.rf2.SnomedRf2ImportRequest.createDb(SnomedRf2ImportRequest.java:250)
...
```
Subsequent call to GET /imports/3c8ed4c1-5ecc-4275-a539-cb317819161c confirms that the import failed
```
{
  "type": "FULL",
  "branchPath": "MAIN",
  "createVersions": true,
  "codeSystemShortName": "SNOMEDCT",
  "id": "3c8ed4c1-5ecc-4275-a539-cb317819161c",
  "status": "FAILED",
  "startDate": "2019-11-03T09:46:44Z",
  "completionDate": "2019-11-03T09:46:44Z"
}
```
Any hints to help me move me forward would be helpful!

Thanks,
Petr

**Comment by cmark** [comment] 2019-11-04 08:01
Hi @psiotwo,

- To configure the HEAP space, please consult the following pages of the official documentation:
https://docs.b2i.sg/snow-owl/index-1/important-settings#setting-the-heap-size
- Could you please post the full stacktrace for the failed RF2 import? It looks like the system failed to initialize the `kotlin/jvm/internal/Intrinsics` class and that's why it is throwing `java.lang.NoClassDefFoundError` errors.

Thanks,
Mark

**Comment by cmark** [comment] 2019-11-04 08:04
Ohh, sorry, I just read your comment again and realized you are using the `b2ihealthcare/snow-owl` image. That is unfortunately deprecated and you should be using these images instead:
https://hub.docker.com/r/b2ihealthcare/snow-owl-oss/tags

Also, could you please try the import with the latest `7.x` image? Thanks!

**Comment by psiotwo** [comment] 2019-11-04 13:27
Hi @cmark, 
trying the latest image, but getting 401 on any request. Tried to use u:'snowowl' and p:'snowowl' as suggested in https://docs.b2i.sg/snow-owl/index-1/index-2/file, but these do not seem to work for me.

**Comment by cmark** [comment] 2019-11-04 13:44
Hi @psiotwo,

How did you start the docker image?
I just tried it again using the latest 7.x image with the following command:
```
$ docker run -p 8080:8080 b2ihealthcare/snow-owl-oss:7.x
```

After that using the `snowowl:snowowl` username and password in the `Authorize` field, I can successfully log in and use the APIs.

Regards,
Mark

**Comment by psiotwo** [comment] 2019-11-04 14:12
Hi @cmark,

I was using docker-compose:
```
version: '2'
services:
  snowowl:
    image: b2ihealthcare/snow-owl-oss:7.1.0
    container_name: snowowl
    ports:
      - 18080:8080
    cpuset: '0'
```

Now I tried to use docker directly as you suggest, but on another port `docker run -p 18080:8080 b2ihealthcare/snow-owl-oss:7.x`. This gives me:

```OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.b2international.index.Activator (file:/usr/share/snowowl/plugins/com.b2international.index_7.2.0.201910311725.jar) to field java.lang.reflect.Field.modifiers
WARNING: Please consider reporting this to the maintainers of com.b2international.index.Activator
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[2019-11-04T14:11:52.560] INFO   Container: 7e64d8a8-83b1-4e74-acb5-b8422f8f5eec org.hibernate.validator.internal.util.Version                    HV000001: Hibernate Validator 5.1.1.Final 
[2019-11-04T14:11:53.086] ERROR  Container: 7e64d8a8-83b1-4e74-acb5-b8422f8f5eec snowowl                                                          null java.lang.ExceptionInInitializerError: null
	at org.hibernate.validator.messageinterpolation.ResourceBundleMessageInterpolator.interpolateExpression(ResourceBundleMessageInterpolator.java:341)
	at org.hibernate.validator.messageinterpolation.ResourceBundleMessageInterpolator.interpolateMessage(ResourceBundleMessageInterpolator.java:279)
	at org.hibernate.validator.messageinterpolation.ResourceBundleMessageInterpolator.interpolate(ResourceBundleMessageInterpolator.java:182)
	at org.hibernate.validator.internal.engine.ValidationContext.interpolate(ValidationContext.java:362)
	at org.hibernate.validator.internal.engine.ValidationContext.createConstraintViolation(ValidationContext.java:271)
	at org.hibernate.validator.internal.engine.ValidationContext.createConstraintViolations(ValidationContext.java:232)
	at org.hibernate.validator.internal.engine.constraintvalidation.ConstraintTree.validateSingleConstraint(ConstraintTree.java:291)
	at org.hibernate.validator.internal.engine.constraintvalidation.ConstraintTree.validateConstraints(ConstraintTree.java:133)
	at org.hibernate.validator.internal.engine.constraintvalidation.ConstraintTree.validateConstraints(ConstraintTree.java:91)
	at org.hibernate.validator.internal.metadata.core.MetaConstraint.validateConstraint(MetaConstraint.java:84)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateConstraint(ValidatorImpl.java:525)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateConstraintsForDefaultGroup(ValidatorImpl.java:465)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateConstraintsForCurrentGroup(ValidatorImpl.java:429)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateInContext(ValidatorImpl.java:381)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validate(ValidatorImpl.java:184)
	at com.b2international.commons.validation.ApiValidation$1.validate(ApiValidation.java:103)
	at com.b2international.commons.config.ConfigurationFactory.validate(ConfigurationFactory.java:234)
	at com.b2international.commons.config.ConfigurationFactory.build(ConfigurationFactory.java:160)
	at com.b2international.commons.config.ConfigurationFactory.build(ConfigurationFactory.java:248)
	at com.b2international.commons.config.ConfigurationFactory.build(ConfigurationFactory.java:151)
	at com.b2international.commons.config.ConfigurationFactory.resolveModuleConfigs(ConfigurationFactory.java:190)
	at com.b2international.commons.config.ConfigurationFactory.build(ConfigurationFactory.java:158)
	at com.b2international.commons.config.ConfigurationFactory.build(ConfigurationFactory.java:248)
	at com.b2international.commons.config.ConfigurationFactory.build(ConfigurationFactory.java:112)
	at com.b2international.snowowl.core.SnowOwl.createConfiguration(SnowOwl.java:235)
	at com.b2international.snowowl.core.SnowOwl.<init>(SnowOwl.java:112)
	at com.b2international.snowowl.core.SnowOwl.create(SnowOwl.java:188)
	at com.b2international.snowowl.server.product.SnowOwlServerActivator.start(SnowOwlServerActivator.java:51)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:842)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:834)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:791)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1013)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:365)
	at org.eclipse.osgi.container.Module.doStart(Module.java:598)
	at org.eclipse.osgi.container.Module.start(Module.java:462)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$1.run(ModuleContainer.java:1820)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$2$1.execute(EquinoxContainerAdaptor.java:150)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1813)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1770)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1735)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1661)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
Caused by: javax.el.ELException: Provider com.sun.el.ExpressionFactoryImpl not found
	at javax.el.FactoryFinder.newInstance(FactoryFinder.java:101)
	at javax.el.FactoryFinder.find(FactoryFinder.java:197)
	at javax.el.ExpressionFactory.newInstance(ExpressionFactory.java:189)
	at javax.el.ExpressionFactory.newInstance(ExpressionFactory.java:160)
	at org.hibernate.validator.internal.engine.messageinterpolation.InterpolationTerm.<clinit>(InterpolationTerm.java:59)
	... 46 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.sun.el.ExpressionFactoryImpl cannot be found by com.b2international.commons_7.2.0.201910311725
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:512)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:423)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:415)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at javax.el.FactoryFinder.newInstance(FactoryFinder.java:87)
	... 50 common frames omitted
```

**Comment by cmark** [comment] 2019-11-04 14:58
Hi @psiotwo,

Thank you for trying out the `docker run` command. So far, we could not reproduce your issue locally.
What kind of operating system and version are you using? 
Which docker version is installed on your system?

Thanks,
Mark

**Comment by psiotwo** [comment] 2019-11-04 15:02
Hi @cmark,

environment below:
`> docker version` gives
```Client: Docker Engine - Community
 Version:           19.03.4
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        9013bf583a
 Built:             Fri Oct 18 15:53:51 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.4
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       9013bf583a
  Built:            Fri Oct 18 15:52:23 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

It is running on an older Ubuntu machine. `uname -a` gives
```
Linux 4.15.0-55-generic #60~16.04.2-Ubuntu SMP Thu Jul 4 09:03:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by cmark** [comment] 2019-11-04 15:17
Hi @psiotwo,

One thing you could try is to pull the image again using `docker-compose pull`.
Not sure if you were using the latest version of the `7.x` image, but it's worth a try.

Cheers,
Mark

**Comment by psiotwo** [comment] 2019-11-04 18:29
Hi @cmark,
confirming that I was using the latest image which produced that error for me. Could you let me know which version of docker you use (although probably irrelevant) ?
Cheers,
Petr

**Comment by psiotwo** [comment] 2019-11-04 23:27
Hi @cmark,
I replicated the failed import resulting in `java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics`. The log is shown here:
https://pastebin.com/67SZ7jRc
Petr

**Comment by cmark** [comment] 2019-11-05 09:31
Hi @psiotwo,

`docker version` gives me:
```
Client: Docker Engine - Community
 Version:           19.03.4
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        9013bf583a
 Built:             Fri Oct 18 15:52:22 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.4
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       9013bf583a
  Built:            Fri Oct 18 15:50:54 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

Thank you for the log. 
The `ClassNotFoundError` is related to how we package our custom mapdb module and apparently that has been fixed after the `7.1.0` release in these commits: https://github.com/b2ihealthcare/snow-owl/commit/1be0b1f433b34aca1de0e07e43cb5b921d416178 https://github.com/b2ihealthcare/snow-owl/commit/93b757d64effcedea0f75e4b380be56d7bfe079c

Unfortunately, due to this error, the RF2 import is broken in the `7.1.0` release.
An attempt to fix the missing `com.sun.el.ExpressionFactoryImpl` has been pushed to the `7.x` branch and a new docker image will be available soon.
Could you please try the RF2 import again in an hour with the latest image built from the `7.x` branch?

Thank you,
Mark

**Comment by cmark** [comment] 2019-11-05 10:59
Hi @psiotwo,

FYI, the latest image has been pushed to Dockerhub. We've successfully deployed it and imported the official SNOMED INT RF2.
Let me know if that version works for you.

Cheers,
Mark

**Comment by psiotwo** [comment] 2019-11-05 11:31
Hi @cmark,
I pulled the latest image, successfully ran it. Seems the API changed in 7.x version comparing to 7.1.0 I was using before. What I can see and access are the various /snowowl/admin endpoints. But I cannot access e.g. /snowowl/snomed-ct/v3 neither /snowowl/fhir endpoints. Was checking the doc (https://docs.b2i.sg/snow-owl/api/core) as suggested in the Swagger page, which still mentions them so I expect I might be doing something terribly wrong ... 
Thank You,
Petr

**Comment by cmark** [comment] 2019-11-05 12:05
Hi @psiotwo,

Yes, that is the new upcoming API documentation site, still work in progress.
You can change to the various API docs by changing the group key in the `api-docs?group=admin` URL at the top from `admin` to one of the following `snomed`, `fhir`, `cis`.

That should show you the usual APIs you were able to browser previously at `/snowowl/snomed-ct/v3/`, `/snowowl/fhir` and `/snowowl/cis`.
The new documentation page will allow seamless navigation between these APIs. (you can track the progress here: https://github.com/b2ihealthcare/snow-owl/tree/feature/api-docs-refactor)

Let me know if you have any further questions.
Best,
Mark

**Comment by psiotwo** [comment] 2019-11-05 14:20
Hi @cmark,
ah yes, of course - thanks for clarification, was just confused by the new Swagger UI ... 

I tried to import Snomed 20190131 Intl edition - first time tried FULL release, second time just SNAPSHOT. In both cases I ended up with some indexing failure after some time of a promising progress ... 

https://controlc.com/709a8da6

**Comment by cmark** [comment] 2019-11-05 14:32
Hi @psiotwo,

Your machine is running low on disk space and the underlying Elasticsearch refuses to write anything to disk when it reaches 95% disk usage (default ES configuration setting).

See line in the attached log:
```
flood stage disk watermark [95%] exceeded on [OtOb20SsSTCO7tDDlw5fdA][elastic-snowowl][/usr/share/snowowl/resources/indexes/elastic-snowowl/data/nodes/0] free: 9.4gb[4.3%], all indices on this node will be marked read-only 
```

The first few lines logged by Elasticsearch actually show the available net space:
```
[2019-11-05T11:26:02.585] INFO   Container: ef1b12df-7bcf-44c2-80c1-18c8b85c2e96 org.elasticsearch.env.NodeEnvironment                            using [1] data paths, mounts [[/ (none)]], net usable_space [9.5gb], net total_space [217.4gb], types [aufs] 
```

9.5Gb is not going to be enough to store the entire FULL RF2 INT data in Snow Owl. Make sure you have at least 50Gb free space before you start the import process. In the end, the final size of your Elasticsearch index will be around 20 GB and you will still have 10-15% of free space available, which will not trigger the read-only flag in the underlying Elasticsearch.

Also, we have a health check endpoint at `GET /snowowl/admin/info`, which returns the health status of the underlying indexes as well, that will show you if there are issues with the indexes.

Let me know if you have any further questions/issues.

Regards,
Mark

**Comment by psiotwo** [comment] 2019-11-06 07:55
Hi @cmark ,
I confirm I was able to import Full release of SNOMED CT Intl. edition. following this thread.
Thanks a lot for your support,
Petr

**Comment by cmark** [comment] 2019-11-06 08:04
Hi @psiotwo,

Great to hear that! 
Should you have any questions or issues, do not hesitate to raise an issue here on GitHub.

Regards,
Mark

**Comment by cmark** [comment] 2019-11-29 08:20
All of the reported issues have been resolved successfully. Closing issue.

**Closed as completed by cmark** 2019-11-29 08:20 UTC
Labels: bug
